### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#9] opened 2016-03-05 17:36 UTC
```
mrocklin@workstation:~/workspace/dec2$ dec2 up --keyname mrocklin --keypair ~/.ssh/anaconda-cluster.pem  --nprocs 4
Launching nodes
DEBUG: Checking that keyname 'mrocklin' exists on EC2
DEBUG: Checking that security group 'dec2-default' exists on EC2
DEBUG: Creating 4 instances on EC2
DEBUG: Tagging instance 'i-84a82f00'
DEBUG: Tagging instance 'i-85a82f01'
DEBUG: Tagging instance 'i-86a82f02'
DEBUG: Tagging instance 'i-87a82f03'
Checking SSH connection to nodes
DEBUG: Checking ssh connection for 52.23.171.227
ERROR: Error connecting to host '52.23.171.227:22'
timed out
```

Things seemed to work better if I, after this, call `dec2 provision`.  Does this mean that timeouts are too optimistic?

**Comment by danielfrg** [comment] 2016-03-07 17:10
Was this on python 3? If true, I think this is a duplicate of https://github.com/dask/dec2/issues/5.

Your solution is correct, call `dec2 provision` after.

**Comment by mrocklin** [comment] 2016-03-07 17:14
Ah, ok.  Yes, this was Python 3.  Suggestions for a temporary workaround?  Perhaps an informative error message or is there a way to call `dec2 provision` for the user directly in this case?

**Comment by danielfrg** [comment] 2016-03-07 17:17
`dec2 provision` is the step that is failing, thats why waiting for SSH to become available and do it again works. Waiting for SSH on python3 is not working. Is a better error message enough for you?

**Comment by mrocklin** [comment] 2016-03-07 17:17
I'll take anything I can get :)

**Comment by danielfrg** [comment] 2016-03-07 17:34
Solved in https://github.com/dask/dec2/commit/13dc7ddd824bb99b307ebca8b095f0efd2cc89b0 by catching the exception and retrying until SSH is available. It should be solved on https://github.com/dask/dec2/pull/8

**Comment by danielfrg** [comment] 2016-03-07 19:01
Closing based on feedback on: https://github.com/dask/dec2/issues/10#issuecomment-193381487

**Closed as completed by danielfrg** 2016-03-07 19:01 UTC
